### PR TITLE
Update alts.json to update Plausible Analytics details

### PR DESCRIPTION
**Pull request by metmarkosaric**
Updating Plausible Analytics repo URL and other details.

### CODE REVIEW

**Comment by jcklpe** [comment]
@metmarkosaric  Hey sorry, the auto checks failed. If you can update the pull request and not have the deployment fail or whatever I can approve the merge pull request etc. I'm just a volunteer helping groom tickets.

**Comment by metmarkosaric** [comment]
Thanks @jcklpe! Seems to have worked fine this time!

**Comment by metmarkosaric** [comment]
hi @jcklpe! did you have a chance to take a look at this? Plausible Analytics details are outdated on the site so would be nice to get it updated. let me know if there's something else i can help with please, thanks!

**Comment by jcklpe** [comment]
@metmarkosaric  hey sorry for the delay :) Thank you for contributing!

**Pull request merged**
