### PR TITLE
Add automatisch

### PR DESCRIPTION
**Pull request by Squishibutz**
Automatisch is a business automation tool that lets you connect different services like Twitter, Slack, and more to automate your business processes.

### CODE REVIEW

**Comment by jcklpe** [comment]
@Squishibutz  We have a failed check. I don't actually do any of the code on this project, I just help maintain the github issues and stuff. Can you check on that? If you can pass the checks I'll merge.

**Comment by Squishibutz** [comment]
@jcklpe i have no access to the vercel logs i can only see that the deployment failed. Can you give me the detailed log?

**Comment by jcklpe** [comment]
@Squishibutz I don't either maybe @junaid33 can help.

**Comment by Squishibutz** [comment]
> Error: Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.

I guess you need to do this in Verce since there is no .node-version file anywhere in the project

**Pull request merged**
