### PR TITLE
Adding Appwrite an open source Backend as a Service

### PR DESCRIPTION
**Pull request by lohanidamodar**
Appwrite is an open source, self-hosted backend as a service.

### CODE REVIEW

**Comment by kogeletey** [comment]
This is not an alternative to the design application, you need to go to the heroku and render category

**Comment by lohanidamodar** [comment]
@kogeletey I couldn't understand what you mean by heroku? couldn't find any link. I tried running locally but I get this error `Error: useCMS could not find an instance of CMS`

So I instead added id to the new category, this seems to have fixed the previous issue. Please check and let me know if there's a better way to do it.

Thank you

**Comment by kogeletey** [comment]
Yes it's good. More alternatives will need to be added. But merge, I still can't

**Comment by lohanidamodar** [comment]
> Yes it's good.Then we will add more alternatives. But merge, I still can't

We need more alternatives before we merge? I can add more like Parse server and others

**Comment by kogeletey** [comment]
Well no. You misunderstood, I just don't have merge rights. But on before would beg

**Comment by kogeletey** [comment]
Update your repository

**Comment by jcklpe** [comment]
I can merge this once it passes it's automated  checks.

**Comment by lohanidamodar** [comment]
@jcklpe hey, I'm not sure why it's failing, now I'm able to run it locally. Can you help me diagnose the issue. Thanks!

**Comment by lohanidamodar** [comment]
Hey is there anything I can do further? Thanks!

**Comment by jcklpe** [comment]
@lohanidamodar : Apologies. I was catching up on PR and I accepted a newer PR than yours and it seems to have caused an error on deploy. If you update I will get this pr merged ASAP. Again, my fault!

**Comment by lohanidamodar** [comment]
@jcklpe Hi thanks for merging, and sorry to bother you, however I am seeing one issue, is it because i didn't completed the update before mergin?

I see the alternatives section I added when I go to https://opensource.builders/edit/
however, I don't see, and don't find when I search for Appwrite or Firebase?

Let me know if you have any idea, and If I can do anything to help fix.
Thank you

**Comment by jcklpe** [comment]
@lohanidamodar : I think the issue is that I merged a change that didn't come from a later commit, so now trying to merge creates a conflict. That's my guess. If you do a fetch and pull from the current dev and then try to re merge in your changes then do a pull request I believe that will fix it (though I'm not the best with git so I could be wrong. I mostly volunteer on this project as a janitor of sorts)

**Comment by lohanidamodar** [comment]
> @lohanidamodar : I think the issue is that I merged a change that didn't come from a later commit, so now trying to merge creates a conflict. That's my guess. If you do a fetch and pull from the current dev and then try to re merge in your changes then do a pull request I believe that will fix it (though I'm not the best with git so I could be wrong. I mostly volunteer on this project as a janitor of sorts)

no problem let me try

**Pull request merged**
