### PR TITLE
Added alternatives to GoodReads

### PR DESCRIPTION
**Pull request by teampolyglot**
Adding OpenLibrary and LearnAwesome as open-source alternatives to GoodReads

### CODE REVIEW

**Comment by jcklpe** [comment]
@eshnil hey checks failed. Can you address the issue?

**Comment by nileshtrivedi** [comment]
@jcklpe Can you guide me on how to debug? The JSON change looks okay to me. The Vercel link is asking me to sign up and I don't know what that is about.

**Comment by jcklpe** [comment]
@nileshtrivedi : Sorry I am not familar with the build pipeline etc on that. I just volunteer on the side to help tend the github issues. I basically pass along whatever PRs come through that pass their checks and don't have anything weird in them. I can not help you specifically on debugging this issue. Also I am not clear on what your relationship is with the original PR maker @eshnil   ? Is that an alternative account name for you or what?  
  
I think this might be something worth pinging @junaid33  on.

**Comment by nileshtrivedi** [comment]
@jcklpe Yes, I am @eshnil. I'm discontinuing that account. Apologies for the confusion. :-)

**Pull request merged**
