### PR TITLE
Add Akaunting as QuickBooks alternative

### PR DESCRIPTION
**Pull request by denisdulici**
Akaunting is a free, online, and open source accounting software designed for small businesses and freelancers. It is built with modern technologies such as Laravel, VueJS, Bootstrap 4, RESTful API, etc. Thanks to its modular structure, Akaunting provides an awesome App Store for users and developers.

### CODE REVIEW

**Comment by boomtow** [comment]
How does this work check changes

**Comment by denisdulici** [comment]
@junaid33 Any reason you've merged PR submitted later than this none?

**Comment by jcklpe** [comment]
@denisdulici  I don't think junaid is really keeping up with this repo anymore, but I can merge if you can resolve the conflicts on this pr

**Comment by denisdulici** [comment]
Thanks @jcklpe but it seems that @junaid33 has changed the structure before merging PR so shame on him!

**Comment by junaid33** [comment]
@denisdulici My mistake. I'll remember next time to merge PRs before any structure changes. Also, I have not abandoned the project. I added categories and n-to-n a few weeks back. I'll be adding pagination this week and then go thru and add all the alternatives.

**Comment by denisdulici** [comment]
Resent here https://github.com/junaid33/opensource.builders/pull/307

**Pull request closed without merging**
