### PR TITLE
Added Typesense as an alternative to Algolia

### PR DESCRIPTION
**Pull request by jasonbosco**
Hello,

Thank you for building this catalog! Added our open source search engine project to it.

### CODE REVIEW

**Comment by jcklpe** [comment]
@jasonbosco : hey cool project. Unfortunately the vercel deployment checks failed. Do you know what the issue is? (I'm just a volunteer who helps out with the github tickets. I don't actually know very much about how the deployment works beyond that

**Comment by jasonbosco** [comment]
@jcklpe I'm not sure why the vercel preview failed unfortunately. Clicking on "Details" in the Github Status section next to Vercel shows me a 404, which I'm guessing might be because I don't have access to see deployment logs in Vercel. 

I tried running this branch locally and it boots up properly and shows me the entry I added. So this seems to be something that's isolated to Vercel. If I can get the vercel deployment logs, I can help debug further.

**Comment by jcklpe** [comment]
@junaid33  needs to tag in on this issue.

**Comment by junaid33** [comment]
Looks like yarn was the issue. NPM is working and it should be fixed now.

**Comment by jasonbosco** [comment]
Thanks @junaid33. Any way to retrigger the vercel deployment so the github check passes?

**Comment by jasonbosco** [comment]
@junaid33 Looks like all checks pass now. Mind taking a look at this?

**Pull request merged**
