### PR TITLE
Add Cypress and Sorry Cypress alternative

### PR DESCRIPTION
**Pull request by agoldis**

### CODE REVIEW

**Comment by junaid33** [comment]
I don’t see the commercial app that’s Sorry Cypress is an alternatives to.

**Comment by agoldis** [comment]
https://www.cypress.io/pricing

**Comment by junaid33** [comment]
But Cypress is open-source itself. The commercial app has to be proprietary.

**Comment by agoldis** [comment]
Cypress has two components:

1. the agent that runs the test - it is open source
2. the dashboard - it is proprietary, not open source, paid product (https://www.cypress.io/dashboard/)
3. Here's the pricing cypress.io/pricing for the commercial part of cypress.

Sorry-Cypress is a free, open-source alternative to Cypress Dashboard.

Hope that helps :)

**Comment by agoldis** [comment]
@junaid33 gently reminding

**Comment by junaid33** [comment]
Hey Andrew, upon more research, it seems Cypress is running an open-core model for their open-source software. That means the main application is open-sourced and they are monetizing using their dashboard. To qualify as a commercial software, all parts have to be proprietary. If I allow this submission, I'll have to allow other fully open-sourced products as alternatives to open-core products. This would end up confusing users in my opinion. I will keep this in mind and if things change, I will reopen this issue.

**Comment by agoldis** [comment]
@junaid33 I see your point, and it makes sense. Let me share how I see the situation as an open-source alternative tool maintainer:

>  To qualify as a commercial software, all parts have to be proprietary.

1. You'd probably make it clear for contributors what projects do you want to appear in the list you've created - it seems arbitrary when you expose that definition in the midst of PR.

2. You have already "leaked" open-core solution into your list. `npm` operates in manner similar to Cypress, its core is even more open to public. You'll have to remove `npm` to be compliant and sound with your own definition. Otherwise one can claim that your judgement is biased and lacks integrity.

> If I allow this submission, I'll have to allow other fully open-sourced products as alternatives to open-core products

3. Cypress is not fully open-source, it is open-core as you've stated yourself. Arguments you've provided are contradicting,  no offence!

Anyway, thanks for your initiative! 😉

**Pull request closed without merging**
